# Generated by Django 4.0.3 on 2022-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_playback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playback',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='song',
            name='categories',
            field=models.ManyToManyField(to='main_app.category'),
        ),
        migrations.AlterField(
            model_name='playback',
            name='time',
            field=models.DateField(verbose_name='playback date'),
        ),
    ]
